# CORE BRIDGE
[[test.genesis]]
address = "Bridge1p5gheXUvJ6jGWGeCsgPKgnE3YgdGKRVCMY9o"
program = "./core/core_bridge.so"

[[test.validator.account]]
address = "FKoMTctsC7vJbEqyRiiPskPnuQx2tX1kurmvWByq5uZP"
filename = "./core/bridge_config.json"

[[test.validator.account]]
address = "6MxkvoEwgB9EqQRLNhvYaPGhfcLtBtpBqdQugr3AZUgD"
filename = "./core/guardian_set.json"

[[test.validator.account]]
address = "GXBsgBD3LDn3vkRZF6TfY5RqgajVZ4W5bMAdiAaaUARs"
filename = "./core/fee_collector.json"

# TOKEN BRIDGE
[[test.genesis]]
address = "B6RHG3mfcckmrYN1UhmJzyS1XX3fZKbkeUcpJe9Sy3FE"
program = "./token/token_bridge.so"

[[test.validator.account]]
address = "3GwVs8GSLdo4RUsoXTkGQhojauQ1sXcDNjm7LSDicw19"
filename = "./token/token_config.json"

[[test.validator.account]]
address = "7UqWgfVW1TrjrqauMfDoNMcw8kEStSsQXWNoT2BbhDS5"
filename = "./token/emitter_eth.json"

[[test.validator.account]]
address = "BmRvjCA2cQ1qUNAMVAnPgmjATSBPa2pxE3Q7bRoSGFED"
filename = "./token/emitter_bsc.json"

# METAPLEX Metadata Account
[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
filename = "./thirdparty/mpl_token_metadata.so"

# NFT BRIDGE